### ISSUE TITLE
Fix mobile

### ISSUE THREAD

**Issue by Odyssey346** [ProjectSegfault/website#35]
We've received a couple of complains about mobile not having a "Menu" button. We used to have one, and we could probably just revive that code.

**Comment by akisblack** [comment]
we could use svelte-hamburgers if we wanted an easy implementation but anything involving a menu button would require a full refactor of the navbar

**Comment by Odyssey346** [comment]
svelte hamburger lmaotry it igSendt fra min Galaxy
