### ISSUE TITLE
[Suggestion] Add a text that changes every time the page gets reloaded.

### ISSUE THREAD

**Issue by Midou36O** [ProjectSegfault/website#45]
Snippet of code:
https://stackoverflow.com/questions/54289294/random-new-text-on-page-refresh-and-page-load
(This is optional and doesn't break the website when js is disabled.)

**Comment by Odyssey346** [comment]
what's the point?

**Comment by akisblack** [comment]
to be honest, this is something that a 90s website would have

**Comment by Odyssey346** [comment]
could be good for an april fools joke where we make our website look 90s, if we make it that far

**Comment by Midou36O** [comment]
Closed, move issues to gitea.
